// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxukwhaowopkoutjbhwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4dWt3aGFvd29wa291dGpiaHdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNDQ1NDAsImV4cCI6MjA1ODcyMDU0MH0.bpksB6Z1SrO16ovsva0_wi707zvIw9rKhlc091ab4Yg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);